# Generated by Django 5.0.2 on 2024-03-02 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_company', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['name_company'],
            },
        ),
        migrations.CreateModel(
            name='ProductComposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_composition', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_season', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SizeCloth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_cloth', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SizeShoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_shoes', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_prod', models.CharField(max_length=50)),
                ('article', models.CharField(max_length=50)),
                ('description', models.TextField(null=True)),
                ('color', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('product_count', models.IntegerField(max_length=100)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.category')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.company')),
                ('product_composition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.productcomposition')),
                ('season', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.season')),
                ('size_cloth', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.sizecloth')),
                ('size_shoes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.sizeshoes')),
            ],
            options={
                'ordering': ['name_prod'],
            },
        ),
    ]
