# Generated by Django 5.0.2 on 2024-03-10 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_alter_sizecloth_size_cloth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_count',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sizeshoes',
            name='size_shoes',
            field=models.IntegerField(),
        ),
    ]
