# Generated by Django 5.0.2 on 2024-03-10 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_product_product_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sizecloth',
            name='size_cloth',
            field=models.IntegerField(default=0),
        ),
    ]
