# Generated by Django 5.0.2 on 2024-03-16 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_cart_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='product',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
